### PR TITLE
Create Kiss.ts

### PR DESCRIPTION
**Pull request by thinc5**
kiss Owo

### CODE REVIEW

**Comment by Assasindie** [comment]
Hello, Please fix the bugs so that the checks will work and rename the export default class and the constructor relating to your command.
Thank you

**Comment by thinc5** [comment]
do i have to make a new pull request now or does it update

what do

**Comment by thinc5** [comment]
also stop bully please

**Comment by Assasindie** [comment]
just make it work like? ??????

**Comment by thinc5** [comment]
> just make it work like? ??????

if you dont have anything positive to say don't say anything at all sweaty ok! :)

**Comment by Assasindie** [comment]
if you dont have anything that works dont post it at all sweaty ok! :)

**Pull request closed without merging**
